### ISSUE TITLE
CSS Grid - trouble with image displaying

### ISSUE THREAD

**Issue by objectprogr** [objectprogr/30dayschallenge#1]
#### Branch - [link](https://github.com/objectprogr/30dayschallenge/tree/day9_10_simpleResponsiveWeb)

I have a trouble with my image which I can displaying after click `Display image` button on my website.
Image is not responsive. I add CSS Grid, but I must doing something wrong, but I dont know what, because dont work.

#### Screenshot:
![troublewithimage](https://user-images.githubusercontent.com/23135468/48067140-c2f33a00-e1cf-11e8-8e75-34d5345dbaf1.PNG)

**Comment by youngestdj** [comment]
I submitted a PR. https://github.com/objectprogr/30dayschallenge/pull/2
![img-responsive](https://user-images.githubusercontent.com/8430993/48100069-1b532780-e222-11e8-999e-df438ebf0a89.PNG)

**Comment by objectprogr** [comment]
Thank you!
